### ISSUE TITLE
How would i schedule a notification on particular date and time?

### ISSUE THREAD

**Issue by SatyaRamprasad** [mundipagg/OneSignal-CSharp-SDK#30]
How would i schedule a notification on particular date and time?

Any help @lucasnobredev @mvrmoreira @AlfonsoML

**Comment by AlfonsoML** [comment]
Please, don't mention me for your questions.

**Comment by victorldomingues** [comment]
you will fill a SendAfter property of the NotificationCreateOptions class

```
  var options = new NotificationCreateOptions
            {
                AppId = _appId,
                Contents = contents,
                Headings = headings,
                IncludedSegments = includedSegments,
                Data = data,
                SendAfter = **scheduleDate**,
                IncludePlayerIds = new[] {"x.y.z"}
            };
```

**Comment by SatyaRamprasad** [comment]
> Please, don't mention me for your questions.

**Comment by SatyaRamprasad** [comment]
> > Please, don't mention me for your questions.

**Comment by SatyaRamprasad** [comment]
When i add this option, getting response as id =null,recipients = 0.
     options.SendAfter = new DateTime(2019, 5, 1, 03, 38, 0, DateTimeKind.Local);
Is this format okay?

**Comment by victorldomingues** [comment]
How is your NotificationCreateOptions object completely? Can you share?

**Comment by SatyaRamprasad** [comment]
[HttpGet]
        [Route("api/Account/OneSignal")]
        public async Task<IActionResult> OneSignal()
        {
            string apiKey = "ZTE5Nzg5NDQtODdlMi00ZTFjLTg3MWQtZTAwZGZmYTMzYjYx";
            string appId = "90b001a7-a864-4636-9648-25463d46aab4";
            var client = new OneSignalClient(apiKey);
            var options = new NotificationCreateOptions();
            options.AppId = Guid.Parse(appId);
            options.IncludePlayerIds = new List<string> { "692996c2-4fc5-43dc-abad-b4693ebe24e5" };
            //options.ActionButtons = new List<ActionButtonField>();
            //options.ActionButtons.Add(new ActionButtonField { Text = "Accept", Id = "101" });
            //options.ActionButtons.Add(new ActionButtonField { Text = "Reject", Id = "102" });
            options.Headings = new Dictionary<string, string>();
            options.Headings.Add(LanguageCodes.English, "New Notification!");
            //options.Subtitle = new Dictionary<string, string>();
            //options.Subtitle.Add("subtitle", "New SubTitle!");
            options.Contents = new Dictionary<string, string>();
            options.Contents.Add("Page", "New Page2!");
            options.Contents.Add(LanguageCodes.English, "This will push a real notification directly to your device.This will push a real notification directly to your device.");
            //options.SmallAndroidIcon = "icon";
            //options.AndroidSound = "Default";
            //options.AndroidLedColor = "#ffffff";
            options.SendAfter = new DateTime(2019, 5, 1, 03, 38, 0, DateTimeKind.Local);
            //options.DelayedOption = DelayedOptionEnum.LastActive;
            //options.DeliveryTimeOfDay = "10:38PM";
            options.TimeToLive = 2419200; //Max Time
            //options.Priority = 10; //High
            var result = client.Notifications.Create(options);
            return Ok(result);
        }

**Comment by victorldomingues** [comment]
In my perspective this is correct.

Check the players if they are correct or try to send by segments.

It is necessary to have an application and valid signatures for testing to be able to receive the id of the notifications.

I recommend that you send the scheduled notification to check on the OneSignal portal the date it was saved on their server, and then make the adjustment for your timezone.

Now if OneSingal is not accepting your notification it may be something else wrong but the scheduling date I believe is in compliance.

**Comment by victorldomingues** [comment]
I did a test with your example in my application and the message was scheduled

![image](https://user-images.githubusercontent.com/11246710/57019758-c6570380-6bfd-11e9-9a20-7a81c532535b.png)

**Comment by SatyaRamprasad** [comment]
Thanks @victorldomingues 
Working now....
