### ISSUE TITLE
Sending to single device

### ISSUE THREAD

**Issue by PaulVipond** [mundipagg/OneSignal-CSharp-SDK#4]
Hi. Could you add an example of how to send to a single device? I'm using android if it makes a difference. Many thanks.

**Comment by rohitsies** [comment]
Have someone figured out how to send notification to specific device using this sdk??

**Comment by PaulVipond** [comment]
It's mildly platform specific. Some code for android:

```

        public async Task<bool> SendNotification(PushMessageTarget target, string payload)
        {
            var url = await _settingsCache.GetCachedValueFromKeyAsync<string>("PushNotificationUrl");
            var auth = await _settingsCache.GetCachedValueFromKeyAsync<string>("PushNotificationAuth");
            var appId = await _settingsCache.GetCachedValueFromKeyAsync<string>("PushNotificationAppId");
            var fetchTimeout = await _settingsCache.GetCachedValueFromKeyAsync<long>("HttpFetchTimeout");

            payload = Crypto.ToBase64(payload);
            string pushApiContent = $"{{ \"app_id\": \"{appId}\", \"contents\": {{\"en\": \"{payload}\"}}, \"include_android_reg_ids\": [\"{target.DeviceMessagingToken}\"] }}";
            var content = new StringContent(pushApiContent, Encoding.UTF8, "application/json");

            var httpMessage = new HttpRequestMessage(HttpMethod.Post, url);
            httpMessage.Content = content;
            httpMessage.Headers.Authorization = new AuthenticationHeaderValue("Basic", auth);

            Timeout = TimeSpan.FromMilliseconds(fetchTimeout * 1000L);
            HttpResponseMessage response = await SendAsync(httpMessage);

            // Throws an exception if we get anything other than success
            response.EnsureSuccessStatusCode();

            return true;

```

This is using the message token rather than a player ID which I was advised to. I prefer the message token so I don't create a dependency on the OneSignal SDK at the client. I.e. standard push will work. I encoded the message payload in Base64 to avoid confusing the Json string.

**Comment by victorldomingues** [comment]
If you have saved the id of the device in your database when the user accepts to receive push notifications, it is easy to send with the playerid.
You need to load the ids that you want to send a notification to and pass as a parameter in the construct options of the Create method in the instance of the push notification object



>###  // My Push Notification Class
```
Public class PushNotification
    {
        Public string Title {get; Set; }
        Public string Description {get; Set; }
        Public IList <string> DeviceIds {get; Set; }
    }
```
> ###  // In my push notificaion manager, my send method
```
Public NotificationCreateResult Send (PushNotification push) {
            Var contents = new Dictionary <string, string>
            {
                ["En"] = push.Description
            };

            Var headings = new Dictionary <string, string>
            {
                ["En"] = push.Title
            };

            Var data = new Dictionary <string, string>
            {
                ["State"] = push.State,
                ["Id"] = push.Entity
            };

            Var includedSegments = new List <string> {""};
            Var options = new NotificationCreateOptions {
               AppId = _appId,
               Contents = contents,
               Headings = headings,
               Date = date,
               IncludePlayerIds = push.DeviceIds
            };
            Return _oneSignalClient.Notifications.Create (options);
}
```
> ### // Use
https://github.com/mundipagg/OneSignal-CSharp-SDK/blob/master/src/OneSignal.CSharp.SDK/Resources/Notifications/NotificationCreateOptions.cs

**Comment by kamlesh10** [comment]
@victorldomingues I followed your method. 
I get this:
{
    "recipients": 0,
    "id": null
}
as a result.
am I doint something wrong?

**Comment by victorldomingues** [comment]
@kamlesh10 
For me it has worked this way.

Check your dashboard in OneSignal whether the message was delivered to the appropriate device or is in a queue.

Because I have not returned a bad request, I believe you have been submitting it correctly.

Make sure that the device id is actually registered with OneSignal if your application keys and id are correct.

However you can compare the data of your request through this library with the model data available in the OneSignal [documentation](
https://documentation.onesignal.com/reference#section-send-based-on-onesignal-playerids-create-notification) .
