### ISSUE TITLE
Added remaining notification properties mentioned in OneSignal REST API 

### ISSUE THREAD

**Issue by HEBOS** [mundipagg/OneSignal-CSharp-SDK#7]
Hi,
I downloaded complete project and added all missing notification properties according to current OneSignal API.
Please be so kind and add it to project, and publish new build on NuGet.
Attached files belong to "Notifications" folder:
[OneSignalRestApiComplete.zip](https://github.com/mundipagg/OneSignal-CSharp-SDK/files/728036/OneSignalRestApiComplete.zip)

**Comment by HEBOS** [comment]
Please take the this updated attachement where I formatted XML comments also.
Also, please when building include option to generate XML comments to support intellisense suggestion as AlfonsoML suggested.
[OneSignalRestApiComplete.zip](https://github.com/mundipagg/OneSignal-CSharp-SDK/files/728125/OneSignalRestApiComplete.zip)

**Comment by mvrmoreira** [comment]
Hi I merged your PR and added the new version to nuget but build is printint a lot of warnings, see them at: https://ci.appveyor.com/project/MundiPagg/onesignal-csharp-sdk/build/0.5.31/messages

Sorry but I have no idea why, could you help us?

**Comment by HEBOS** [comment]
Hi Matheus,

 

I've completed missing XML documentation and added supported languages that were missing.

 

Hrvoje Matić, mag. inf.

E:  <mailto:ibicom@ibicom.hr> ibicom@ibicom.hr

T: +385 (0)1 6182-501

M: +385 (0)91 201-9678

**Comment by mvrmoreira** [comment]
Great! Closing issue.
